learn_config:
  learn_acf: false
  learn_both: false
  learn_marginal: true
loss_config:
  kl_type: kl
  nr_acf_lags: 35
  num_KL_samples: 5000
  p: 2
  use_acf_directly: true
  use_kl_div: false
model_config:
  dropout_rate: 0.05
  final_output_size: 3
  linear_layer_sizes:
  - 16
  - 8
  - 4
  lstm_hidden_size: 64
  mean_aggregation: true
  model_name: LSTMModel
  num_lstm_layers: 2
  with_theta: false
optimizer:
  lr: 0.0025
  name: adam
prng_key: 37494
train_config:
  n_iterations: 35001
trawl_config:
  acf: sup_IG
  acf_prior_hyperparams:
    distr_name: uniform
    eta_prior_hyperparams:
    - 10.0
    - 20.0
    gamma_prior_hyperparams:
    - 10.0
    - 20.0
  batch_size: 64
  marginal_distr: NIG
  marginal_distr_hyperparams:
    beta_prior_hyperparams:
    - -5.0
    - 5.0
    distr_name: uniform
    loc_prior_hyperparams:
    - -1.0
    - 1.0
    scale_prior_hyperparams:
    - 0.5
    - 1.5
  seq_len: 1500
  tau: 1.0
  theta_size: 5
  trawl_process_type: sup_ig_nig_5p
val_config:
  val_freq: 750
  val_n_batches: 40
